language: node_js
node_js:
  - "0.10"
install:
  - "rm -r dist"
  - "npm install"
  - "bower install"
  - "npm run-script dist"
script:
  - npm run-script test
env:
  global:
  - BROCCOLI_ENV="production"
  - EMBER_ENV="production"